import { Inter } from "next/font/google";
import "../scss/globals.scss";

const inter = Inter({ subsets: ["latin"] });
import Fav from "@/app/Favicon/Favicon.png";

export const metadata = {
  title: "MINI-ROUTING-NEXT",
  description: "Generated by Arham Ullah khan",
  icons: [{ rel: "icon", url: Fav.src }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
